title: lowply.github.io
description: lowply.github.io
permalink: /:categories/:year/:month/:title/
timezone: Asia/Tokyo
url: https://lowply.github.io

sass:
  style: compressed

exclude:
  - bin
  - Makefile
  - README.md

plugins:
  - jekyll-feed

assets: https://lowply.s3-ap-northeast-1.amazonaws.com/lowply.github.io/assets
