title: lowply.github.io
description: lowply.github.io
permalink: /:categories/:year/:month/:title/
twitter_username: lowply
github_username:  lowply
timezone: Asia/Tokyo

url: https://lowply.github.io

sass:
  style: compressed

exclude:
  - bin
  - Makefile

plugins:
  - jekyll-last-modified-at

assets: https://lowply.s3-ap-northeast-1.amazonaws.com/lowply.github.io/assets
