# theme.toml
name = "Furniture"
license = "MIT"
licenselink = "https://github.com/lowply/furniture/blob/master/LICENSE"
description = "Furniture - A hugo theme for lowply.github.io"
homepage = "https://github.com/lowply/furniture/"
tags = ["blog"]
min_version = 0.15

[author]
  name = "lowply"
  homepage = "https://github.com/lowply"
