baseurl = "https://lowply.github.io/"
languageCode = "ja"
title = "lowply.github.io"
theme = "furniture"
publishDir = "../"

[permalinks]
	blog = "/blog/:year/:month/:filename/"
	photo = "/photo/:filename/"

[taxonomies]
	category = "categories"

[author]
	name = "Sho Mizutani"
	headshot = "/images/heimat_s.jpg"
	bio = "hello"

[params]
	twitter = "lowply"
	github = "lowply"
	gaid = "UA-258121-9"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
